# PILOT-OPTIMIZED CONFIGURATION
# Generated by display diagnostic tool

# Screen parameters - PILOT OPTIMIZED
SCREEN_PARAMS = {
    'size': [1024, 768],
    'fullscr': False,
    'color': [0, 0, 0],
    'units': 'pix',
    'allowGUI': True,
    'winType': 'pyglet'
}

# Text styling - PILOT OPTIMIZED
TEXT_STYLE = {
    'font': 'Arial',
    'height': 20,
    'color': 'white',
    'wrapWidth': 924,
    'alignText': 'left',
    'anchorHoriz': 'left'
}
